services:
  server:
    image: jangxx/vrc-avatar-remote-server:latest
    ports:
      - "9001:9001/udp"
      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - "./config:/data/config"
      - "./icons:/data/icons"
    networks:
      - default
  cloudflared-quick:
    image: cloudflare/cloudflared
    profiles:
      - cloudflare-quick
    command: tunnel --url http://server:8080
    restart: "unless-stopped"
    networks:
      - default
  cloudflared:
    image: cloudflare/cloudflared
    profiles:
      - cloudflare
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN --url http://server:8080
    restart: "unless-stopped"
    env_file: [ ".env" ]
    networks:
      - default

networks:
  default:
    driver: bridge