services:
  vrc-avatar-remote-server:
    image: jangxx/vrc-avatar-remote-server:1.1.0
    ports:
      - "9001:9001/udp"
      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - "./config:/data/config"
  cloudflared-quick:
    image: cloudflare/cloudflared
    profiles:
      - cloudflare-quick
    command: tunnel --url http://vrc-avatar-remote-server:8080
    restart: "unless-stopped"
  cloudflared:
    image: cloudflare/cloudflared
    profiles:
      - cloudflare
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN --url http://vrc-avatar-remote-server:8080
    restart: "unless-stopped"
    env_file: [ ".env" ]
